apiVersion: 1

datasources:
  - name: PCI Postgres
    uid: pci-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
    editable: false
